name: AppImage Build

on:
    push:
        branches:
            - 'master'
        tags:
            - 'v*'
    pull_request:
        branches:
            - 'master'

defaults:
    run:
        shell: bash

env:
    SOURCE_DIR: ${{ github.workspace }}
    ARTIFACT: formaviva_desktop.AppImage
    QT_VERSION: 6.3.2


jobs:
    build:
        runs-on: ubuntu-18.04

        steps:
            -   name: Checkout repo
                uses: actions/checkout@v2

            -   name: Install Qt
                uses: jurplel/install-qt-action@v2
                with:
                    version: ${{ env.QT_VERSION }}
                    host: linux
                    target: desktop
                    arch: gcc_64
                    dir: ${{ runner.temp }}
                    modules: qtwebengine
                    setup-python: false

            -   name: Set up Python
                uses: actions/setup-python@v2
                with:
                    python-version: '3.9'

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install pdm

            -   name: Build with PyInstaller
                run: |
                    make compile

            -   name: Build AppImage
                run: |
                    wget -O appimagetool.AppImage https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
                    chmod +x appimagetool.AppImage
                    mkdir -p AppDir
                    cp dist/formaviva_desktop/* AppDir/
                    cp formaviva_desktop.desktop AppDir/
                    cp formaviva_desktop.png AppDir/
                    ./appimagetool.AppImage AppDir ${{ env.ARTIFACT }}

            -   name: Upload artifact
                uses: actions/upload-artifact@v2
                with:
                    name: ${{ env.ARTIFACT }}
                    path: ${{ env.SOURCE_DIR }}/${{ env.ARTIFACT }}
